export const CREATE_ORDER = "CREATE_ORDER"
export const FETCH_PIZZA_RECIPES = "FETCH_PIZZA_RECIPES"
export const SET_PIZZA_RECIPES = "SET_PIZZA_RECIPES"
export const SET_PIZZA_RECIPES_ERROR = "SET_PIZZA_RECIPES_ERROR"
export const SET_SELECTED_PIZZA = "SET_SELECTED_PIZZA"
export const ADD_TOPPING = "ADD_TOPPING"
export const ADD_PIZZA_TO_CART = "ADD_PIZZA_TO_CART"

